# Generated by Django 3.2.22 on 2024-01-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_favouritebowls'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_bowls',
            field=models.ManyToManyField(blank=True, related_name='favourite_bowls', to='profiles.FavouriteBowls'),
        ),
    ]
