# Generated by Django 3.2.22 on 2024-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(max_length=4, verbose_name='Weight (lbs)'),
        ),
    ]
